M48
; DRILL file {KiCad (6.0.8)} date Mon Oct 31 11:18:17 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-10-31T11:18:17-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.8)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0454
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0866
%
G90
G05
T1
X2.8391Y-2.4721
X3.0666Y-2.4721
T2
X2.7796Y-2.8324
X3.2284Y-2.4387
T3
X2.6773Y-2.3048
X2.6773Y-2.797
X3.2285Y-2.797
T0
M30
